export const navLinks = [
    {
        id:1,
        url:"#hero",
        label:"Home",
    },
    {
        id:2,
        url:"#about",
        label:"About",
    },
    {
        id:3,
        url:"#benefits",
        label:"Benefits",
    },
    {
        id:4,
        url:"#courses",
        label:"Courses",
    },
    {
        id:5,
        url:"#review",
        label:"Testimonials",
    },
    {
        id:6,
        url:"#contact",
        label:"Contact",
    },
]